#!/usr/bin/env python

import plac
import sys

from rganalysis.main import main
from rganalysis.common import logger

def plac_call_main():
    try:
        return plac.call(main)
    except KeyboardInterrupt:
        logger.error("Canceled.")
        sys.exit(1)

if __name__=="__main__":
    plac_call_main()
